import { assert, type PluginInput } from "@varavel/vdl-plugin-sdk";
import * as options from "@varavel/vdl-plugin-sdk/utils/options";
import {
  IMPORT_EXTENSION_VALUES,
  type ImportExtension,
} from "../../shared/imports";
import type { GeneratorOptions, GeneratorTarget } from "../model/types";

/**
 * Resolves and validates the raw plugin options.
 */
export function resolveGeneratorOptions(input: PluginInput): GeneratorOptions {
  const typesImport = options
    .getOptionString(input.options, "typesImport", "")
    .trim();
  assert(
    typesImport, // Truthy check
    'Missing required option "typesImport". Point it to the output generated by varavelio/vdl-plugin-ts.',
  );

  const target = options.getOptionString(input.options, "target", "").trim();
  assert(
    isGeneratorTarget(target),
    'Missing or invalid option "target". Use either "client" or "server".',
  );

  const importExtension = options
    .getOptionString(input.options, "importExtension", "js")
    .trim();
  assert(
    isImportExtension(importExtension),
    `Invalid option "importExtension". Use one of: ${IMPORT_EXTENSION_VALUES.map((value) => JSON.stringify(value)).join(", ")}.`,
  );

  return {
    target,
    typesImport,
    importExtension,
  };
}

/**
 * Reports whether a raw option value is a supported generator target.
 */
function isGeneratorTarget(value: string): value is GeneratorTarget {
  return value === "client" || value === "server";
}

/**
 * Reports whether a raw option value is a supported import extension policy.
 */
function isImportExtension(value: string): value is ImportExtension {
  return (IMPORT_EXTENSION_VALUES as readonly string[]).includes(value);
}
