import type { PluginInput, PluginOutputError } from "@varavel/vdl-plugin-sdk";
import * as options from "@varavel/vdl-plugin-sdk/utils/options";
import {
  IMPORT_EXTENSION_VALUES,
  type ImportExtension,
} from "../../shared/imports";
import type { GeneratorOptions, GeneratorTarget } from "../model/types";

/**
 * Resolves and validates the raw plugin options.
 */
export function resolveGeneratorOptions(input: PluginInput): {
  options?: GeneratorOptions;
  errors: PluginOutputError[];
} {
  const targetRaw = options.getOptionString(input.options, "target", "").trim();
  const typesImport = options
    .getOptionString(input.options, "typesImport", "")
    .trim();
  const importExtensionRaw = options
    .getOptionString(input.options, "importExtension", "js")
    .trim();

  const errors: PluginOutputError[] = [];
  const target = isGeneratorTarget(targetRaw) ? targetRaw : undefined;
  const importExtension = isImportExtension(importExtensionRaw)
    ? importExtensionRaw
    : undefined;

  if (!typesImport) {
    errors.push({
      message:
        'Missing required option "typesImport". Point it to the output generated by varavelio/vdl-plugin-ts.',
    });
  }

  if (!target) {
    errors.push({
      message:
        'Missing or invalid option "target". Use either "client" or "server".',
    });
  }

  if (!importExtension) {
    errors.push({
      message: `Invalid option "importExtension". Use one of: ${IMPORT_EXTENSION_VALUES.map((value) => JSON.stringify(value)).join(", ")}.`,
    });
  }

  if (errors.length > 0 || !target || !importExtension) {
    return { errors };
  }

  return {
    errors: [],
    options: {
      target,
      typesImport,
      importExtension,
    },
  };
}

/**
 * Reports whether a raw option value is a supported generator target.
 */
function isGeneratorTarget(value: string): value is GeneratorTarget {
  return value === "client" || value === "server";
}

/**
 * Reports whether a raw option value is a supported import extension policy.
 */
function isImportExtension(value: string): value is ImportExtension {
  return (IMPORT_EXTENSION_VALUES as readonly string[]).includes(value);
}
